version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: postgres_ebook
    environment:
      POSTGRES_DB: ebook
      POSTGRES_USER: ebook
      POSTGRES_PASSWORD: ebook
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: