version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: postgres_ebooks
    environment:
      POSTGRES_DB: ebooks
      POSTGRES_USER: ebooks
      POSTGRES_PASSWORD: ebooks
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: