spring:
  application:
    name: e_books

  datasource:
    url: jdbc:postgresql://localhost:5432/ebook
    username: ebook
    password: ebook

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    locations: classpath:db/migration


server:
  port: 8080

telegrambot:
  name: BooksExchangeBot
  token: 6382967740:AAEaxxRLBgZjJ1RaY1OzVmw6m5NuKlYaOd0


