spring:
  application:
    name: e_books

  datasource:
    url: jdbc:postgresql://localhost:5437/ebooks
    username: ebooks
    password: ebooks

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    locations: classpath:db/migration


server:
  port: 8080
